platform :ios, '9.0'
use_frameworks!

target 'CEWeibo' do
  pod 'CocoaLumberjack'
  pod 'Masonry' 
  pod 'CFAlertViewController'
  pod 'ProgressHUD'
  pod 'XHPopMenu'
  pod 'AFNetworking', '~> 3.0'
  pod 'JGProgressHUD'
  pod 'SDWebImage', '~> 5.0'
  pod 'MJExtension'
  pod 'MJRefresh'
end
